#!/usr/bin/env bash

function pacman() {
zenity --notification --text "Setting up keyring. This could take a while."
pacman-keyring --init > /dev/null 2>&1 ; pacman-keyring --populate > /dev/null 2>&1 ; sudo pacman -Syu > /dev/null 2>&1
zenity --notification --text "Keyring setup complete." ; zenity --notification --text "Setting up i3"
for action in $(zenity --list --checklist --column  "Select Packages"  --column  "Packages: " TRUE xorg-server TRUE xorg-xinit FALSE rofi TRUE i3-gaps TRUE lightdm TRUE ttf-dejavu FALSE git FALSE axel FALSE memcached TRUE nm-applet FALSE fail2ban FALSE xfce4-terminal FALSE thunar FALSE tor FALSE tuned TRUE ufw TRUE auditd TRUE brightnessctl TRUE feh FALSE firefox FALSE irqbalance FALSE bleachbit FALSE tlp); do
    out="$(echo $action | sed -e 's/|/ /g')"; for final in $out; do
        sudo pacman -S $final -y | zenity --notification  --text " Installing $final" ; done
        case $final in
            i3) sudo systemctl enable nm-applet;;
            tor) sudo systemctl restart tor;;
            fail2ban) sudo systemctl start fail2ban;;
            irqbalance) sudo systemctl enable irqbalance;;
            memcached) sudo systemctl enable memcached;;
            tuned) sudo tuned-adm profile throughput-performance; sudo systemctl enable tuned; sudo service tuned start;;
            tlp) sudo tlp start ; sudo systemctl enable tlp;;
            ufw) sudo ufw enable;;
            auditd) sudo service auditd start && sudo systemctl enable auditd && sudo auditctl -w /etc/passwd -p wa -k user-modify && sudo auditctl -w /boot -p wa -k user-modify && sudo auditctl -w /root -p wa -k user-modify && sudo auditctl -w /etc/ssh -p wa -k user-modify && sudo auditctl -w /etc/security -p wa -k user-modify && sudo auditctl -w /etc/selinux -p wa -k user-modify && sudo auditctl -w /etc/passwd -p wa -k user-modify && sudo auditctl -w /etc/apparmor -p wa -k user-modify && sudo auditctl -l;;
            lightdm) sudo systemctl enable lightdm;;
        esac
    done && zenity --notification --text "i3 setup complete"
}

function apt(){
zenity --notification --text "Updating apt cache"
sudo apt update > /dev/null 2>&1
zenity --notification --text "Cache updated"
zenity --notification --text "Installing i3 and tuning system"
for action in $(zenity --list --checklist --column  "Apt"  --column  "Action: " TRUE apt-transport-https FALSE swapspace FALSE rofi FALSE git FALSE memlockd FALSE unburden-home-dir FALSE auditd FALSE nocache FALSE stacer FALSE axel FALSE libpam-tmpdir FALSE bleachbit FALSE debsums FALSE tuned FALSE tuned-utils FALSE preload FALSE tlp FALSE irqbalance TRUE brightnessctl FALSE fail2ban FALSE memcached FALSE tuned-utils-systemtap FALSE xfce4-4terminal FALSE macchanger TRUE i3 TRUE lightdm TRUE xcompmgr TRUE feh FALSE thunar FALSE tor FALSE apt-transport-tor); do
    out="$(echo $action | sed -e 's/|/ /g')"; for final in $out; do
        sudo apt install $final -y | zenity --notification  --text "Installing $final" ; done
        case $final in
            i3) sudo systemctl enable nm-applet;;
            tor) sudo systemctl restart tor;;
            fail2ban) sudo systemctl start fail2ban;;
            irqbalance) sudo systemctl enable irqbalance;;
            memcached) sudo systemctl enable memcached;;
            tuned) sudo tuned-adm profile throughput-performance;  sudo service tuned start;;
            tlp) sudo tlp start ; sudo systemctl enable tuned ; sudo systemctl enable tlp;;
            ufw) sudo ufw enable;;
            auditd) sudo service auditd start && sudo systemctl enable auditd && sudo auditctl -w /etc/passwd -p wa -k user-modify && sudo auditctl -w /boot -p wa -k user-modify && sudo auditctl -w /root -p wa -k user-modify && sudo auditctl -w /etc/ssh -p wa -k user-modify && sudo auditctl -w /etc/security -p wa -k user-modify && sudo auditctl -w /etc/selinux -p wa -k user-modify && sudo auditctl -w /etc/passwd -p wa -k user-modify && sudo auditctl -w /etc/apparmor -p wa -k user-modify && sudo auditctl -l;;
            lightdm) sudo systemctl enable lightdm;;
            memlockd) sudo systemctl enable memlockd;;
            debsums) sudo debsums -a -s;;
        esac
    done && zenity --notification --text "i3 installed"
}

function extras() {
for action in $(zenity --list --checklist --column  "Extras"  --column  "Git Package: " TRUE tmpmail TRUE translator); do
    out="$(echo $action | sed -e 's/|/ /g')"; for extra in $out; do
        case $extra in
            tmpmail) curl -L "https://raw.githubusercontent.com/sdushantha/tmpmail/master/tmpmail" > tmpmail && chmod +x tmpmail ; zenity --notification --text "Tmpmail setup." && sudo apt install jq w3m xclip -y || sudo pacman -S j1 w3m xclip -y;;
            translator) wget git.io/trans && chmod -x ./trans ; zenity --notification --text "git.io Translator setup.";;
        esac
    done
done
exit 0
}

#################################################################################################################################################

zenity --notification --text "Detecting package manager"
if [ -f "/etc/apt/sources.list" ] ; then
    apt
elif [ -f "etc/pacman.d" ] ; then
    pacman
else
    zenity --notification --text "Package manager not yet supported." ; exit 0
fi
extras
zenity --notification --text "Install Complete!" && read
